name: test74
favicon: null
layout_spectrum: 0.9266863574739546
typography_spectrum: 0.3356911800801754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10431186738424003
  lightness: 0.13346615340560675
  saturation: 0.6225101482123137
  rhythmicContrast: 0.9350983474869281
purpose: []
